### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by c02y** [rayw000/use-proxy#3]
I following the README but failed to make it work.

I got sock5 proxy client(Qv2ray) running in the background, when I want to use it in the terminal, I'll use `proxychains cmd`, I got `socks5 127.0.0.1 1080` in my proxychains.conf file, when I want to use it in my browser, I got SwitchyOmega extension and set it to `socks5 127.0.0.1 1080`.

How can I use it in `use-proxy` in Emacs? (making it globally is OK.)

**Comment by rayw000** [comment]
Hi @c02y 

Glad to know you're interested in this repo 😃. Currently only http(s) proxies are supported. `use-proxy` works by manipulating `url-proxy-services`, and AFAIK socks proxy doesn't respect this variable. It's on my list to make `use-proxy` support socks proxy. It should be simple, but need a little bit more refactor works.

For now, this post may help you: https://gist.github.com/et2010/5d6edeeb284e33343d0a

**Comment by c02y** [comment]
Sorry, I tried the gist months ago, it doesn't work.

**Comment by rayw000** [comment]
Sorry to hear that.

You may need [Privoxy](https://www.privoxy.org), which could conjunct socks and http(s) proxies.

**Comment by c02y** [comment]
Thanks, but I am already using proxychains and Qv2ray.
